name: Build README
on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        # necessary for github-action-til-autoformat-readme
        fetch-depth: 0
    - name: Autoformat README
      uses: cflynn07/github-action-til-autoformat-readme@1.1.0
      with:
        description: |
          어제보다는 하나라도 더 알고있는 zzanzu가 됩시다.
        footer: |
          [1]: https://dogibogi.co.kr
          [2]: https://github.com/zzanzu/TIL
        list_most_recent: 2 # optional, lists most recent TILS below description
        date_format: "2021 Jan 15:04" # optional, must align to https://golang.org/pkg/time/#Time.Format
